### PR TITLE
Added support for inline scripts

### PR DESCRIPTION
**Pull request by piotrze**
Some of plugins(ex. ember-cli-rollbar) add inline script tags in index.html with  {{content-for 'head'}} etc.

Here is support for this.

### CODE REVIEW

**Comment by piotrze** [comment]
Looks like there was a similar [PR](https://github.com/ember-cli-deploy/ember-cli-deploy-json-config/pull/14) for this :(

**Comment by achambers** [comment]
Hi @piotrze. Firstly, thanks for your input. Always appreciated. 

Secondly, yep, we've been through this discussion previously. And [this comment](https://github.com/ember-cli-deploy/ember-cli-deploy-json-config/pull/14#issuecomment-164707337) pretty much sums up our thinking in terms of what the defaults should be. 

I think the more correct approach would be to fix the way we override the defaults. Currently it's all or nothing but maybe we can come up with some way to merge the defaults with custom selectors. 

Would you be open to starting a PR that we can use as a base of discussion around that approach?

@lukemelia / @ghedamat any thoughts?

**Comment by ghedamat** [comment]
@piotrze @achambers sorry for the delay here

I basically agree that we should probably not export scripts by default but instead allow it to be configured by the user

@piotrze are you interested in spiking out a solution?

**Comment by piotrze** [comment]
@ghedamat Will try.

**Comment by achambers** [comment]
@piotrze A suggestion, rather than pumping your time into building a solution straight away, it might be worth having a think about how you might solve the problem, and submitting some sort of PR (or issue) for discussion around the approach so we can settle on the best approach before putting time in to it. I'm personally not sure what the solution should look like yet.

**Comment by jrjohnson** [comment]
@piotrze I'm working on the configuration override solution in #24.  

Just a thought: If you are still willing and able to update this PR I think just removing the changes to the default `jsonBlueprint` in index.js would make it mergeable.  It would then be possible to use it now by overriding the entire jsonBlueprint in an app and then when we have a solution for better configuration management we can just update the docs to include a reference to `captureText`.

**Comment by achambers** [comment]
I believe this can be solved by -> https://github.com/ember-cli-deploy/ember-cli-deploy-plugin/pull/15

Please confirm

**Comment by achambers** [comment]
Duplicated by #25

**Pull request closed without merging**
